<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27417" started-at="2019-07-03T06:08:00Z" finished-at="2019-07-03T06:08:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27417" started-at="2019-07-03T06:08:00Z" finished-at="2019-07-03T06:08:28Z">
      <class name="com.org.pune.MavenSelenium.Facebook">
        <test-method status="FAIL" signature="login()[pri:0, instance:com.org.pune.MavenSelenium.Facebook@5e5792a0]" name="login" duration-ms="19" started-at="2019-07-03T11:38:00Z" finished-at="2019-07-03T11:38:00Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.org.pune.MavenSelenium.LoginFacebook.loginfacebookfunction(LoginFacebook.java:13)
	at com.org.pune.MavenSelenium.Facebook.login(Facebook.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.org.pune.MavenSelenium.Facebook@5e5792a0]" name="setup" duration-ms="26599" started-at="2019-07-03T11:38:00Z" finished-at="2019-07-03T11:38:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.org.pune.MavenSelenium.Facebook@5e5792a0]" name="teardown" duration-ms="773" started-at="2019-07-03T11:38:27Z" finished-at="2019-07-03T11:38:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.org.pune.MavenSelenium.Facebook -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
